server:
  port: 8989
spring:
  datasource:
    master:
      password: 123456
      url: jdbc:mysql://192.168.0.114:3306/a?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: slave1
      password: 123456
      url: jdbc:mysql://192.168.0.114:3306/b?useUnicode=true&characterEncoding=UTF-8
      idle-timeout: 20000
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    - key: slave2
      password: 123456
      url: jdbc:mysql://192.168.0.114:3306/c?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

logging:
  level:
    com:
      yukong:
        chapter5:
          repository: debug